#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$postgres" <<-EOSQL
    CREATE USER $PG_USER WITH SUPERUSER PASSWORD '$PG_PASSWORD' CREATEDB;
    CREATE DATABASE $PG_DB;
    GRANT ALL PRIVILEGES ON DATABASE $PG_DB TO $PG_USER;
EOSQL
